# Generated by Django 4.2.7 on 2024-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='токен'),
        ),
    ]
