# Generated by Django 4.2.7 on 2023-11-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
