# Generated by Django 4.2.7 on 2023-12-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_date_change_alter_product_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.PositiveIntegerField(verbose_name='номер версии'),
        ),
    ]
