# Generated by Django 4.2.7 on 2023-12-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_version_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_relevant',
            field=models.BooleanField(default=False, verbose_name='признак текущей версии'),
        ),
    ]
