# Generated by Django 4.2.7 on 2024-01-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish posts')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
